class FamousQuote {
  static List<String> famousQuotes = [
    "The only way to do great work is to love what you do.",
    "In the midst of chaos, there is also opportunity.",
    "The best way to predict the future is to invent it.",
    "All our dreams can come true if we have the courage to pursue them.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "You miss 100% of the shots you don’t take.",
    "I have not failed. I've just found 10,000 ways that won't work.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The only thing we have to fear is fear itself.",
    "Believe you can and you're halfway there.",
    "The journey of a thousand miles begins with one step.",
    "Change your thoughts and you change your world.",
    "Your time is limited, don't waste it living someone else's life.",
    "It does not matter how slowly you go as long as you do not stop.",
    "What we think, we become.",
    "The only true wisdom is in knowing you know nothing.",
    "The only thing worse than being blind is having sight but no vision.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "Happiness is not something ready-made. It comes from your own actions.",
    "The best revenge is massive success.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "Life is what happens when you're busy making other plans.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Success is stumbling from failure to failure with no loss of enthusiasm.",
    "I'm a greater believer in luck, and I find the harder I work the more I have of it.",
    "The only way to do great work is to love what you do.",
    "If you can't explain it simply, you don't understand it well enough.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only place where success comes before work is in the dictionary.",
    "Opportunities don't happen, you create them.",
    "You miss 100% of the shots you don't take.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "I'm not afraid of storms, for I'm learning how to sail my ship.",
    "The secret of getting ahead is getting started.",
    "It's not what happens to you, but how you react to it that matters.",
    "The best revenge is massive success.",
    "The journey of a thousand miles begins with one step.",
    "Believe you can and you're halfway there.",
    "Do one thing every day that scares you.",
    "You must be the change you wish to see in the world.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It does not matter how slowly you go as long as you do not stop.",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.",
    "The mind is everything. What you think you become.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "What we think, we become.",
    "It is never too late to be what you might have been.",
    "In the midst of chaos, there is also opportunity.",
    "Act as if what you do makes a difference. It does.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "What we think, we become.",
    "It is never too late to be what you might have been.",
    "In the midst of chaos, there is also opportunity.",
    "Act as if what you do makes a difference. It does.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "Do not wait to strike till the iron is hot; but make it hot by striking.",
    "What we think, we become.",
    "It is never too late to be what you might have been.",
    "In the midst of chaos, there is also opportunity.",
    "Act as if what you do makes a difference. It does.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
  ];
}
