class QuestionsToPractice {
  static List<String> questionList = [
    "What is your name?",
    "How are you?",
    "Where are you from?",
    "What do you do?",
    "How old are you?",
    "What time is it?",
    "Where do you live?",
    "What's the weather like?",
    "What's your favorite color?",
    "What's your phone number?",
    "What's your email address?",
    "What do you like to do in your free time?",
    "Do you have any siblings?",
    "Do you have any pets?",
    "What's your favorite food?",
    "What's your favorite movie?",
    "What's your favorite book?",
    "What languages do you speak?",
    "What's your favorite sport?",
    "What's your favorite hobby?",
    "What is your name?",
    "How are you?",
    "Where are you from?",
    "What do you do?",
    "How old are you?",
    "What time is it?",
    "Where do you live?",
    "What's the weather like?",
    "What's your favorite color?",
    "What's your phone number?",
    "What's your email address?",
    "What do you like to do in your free time?",
    "Do you have any siblings?",
    "Do you have any pets?",
    "What's your favorite food?",
    "What's your favorite movie?",
    "What's your favorite book?",
    "What languages do you speak?",
    "What's your favorite sport?",
    "What's your favorite hobby?",
    "What is your name?",
    "How are you?",
    "Where are you from?",
    "What do you do?",
    "How old are you?",
    "What time is it?",
    "Where do you live?",
    "What's the weather like?",
    "What's your favorite color?",
    "What's your phone number?",
    "What's your email address?",
    "What do you like to do in your free time?",
    "Do you have any siblings?",
    "Do you have any pets?",
    "What's your favorite food?",
    "What's your favorite movie?",
    "What's your favorite book?",
    "What languages do you speak?",
    "What's your favorite sport?",
    "What's your favorite hobby?",
    "What is your name?",
    "How are you?",
    "Where are you from?",
    "What do you do?",
    "How old are you?",
    "What time is it?",
    "Where do you live?",
    "What's the weather like?",
    "What's your favorite color?",
    "What's your phone number?",
    "What's your email address?",
    "What do you like to do in your free time?",
    "Do you have any siblings?",
    "Do you have any pets?",
    "What's your favorite food?",
    "What's your favorite movie?",
    "What's your favorite book?",
    "What languages do you speak?",
    "What's your favorite sport?",
    "What's your favorite hobby?"
        "What's your favorite hobby?",
    "What is your name?",
    "How are you?",
    "Where are you from?",
    "What do you do?",
    "How old are you?",
    "What time is it?",
    "Where do you live?",
    "What's the weather like?",
    "What's your favorite color?",
    "What's your phone number?",
    "What's your email address?",
    "What do you like to do in your free time?",
    "Do you have any siblings?",
    "Do you have any pets?",
    "What's your favorite food?",
    "What's your favorite movie?",
    "What's your favorite book?",
    "What languages do you speak?",
    "What's your favorite sport?",
  ];
}
